version: "3.8"

networks:
  lan:

services:
 

  frontend:
    build: 
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./src:/app/src
    environment:
      ASPNETCORE_URLS: "http://*:80"
    networks:
      - lan
    ports:
      - 3000:3000

    
