version: "3.8"

networks:
  lan:

services:
  mssql:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      SA_PASSWORD: "P@ssword123"
      ACCEPT_EULA: "Y"
    networks:
      - lan

  mssqlcli:
    image: mcr.microsoft.com/mssql-tools:latest
    command: bash
    networks:
      - lan

  ef:
    build: ./
    command: "./wait-for-it.sh mssql:1433 -- dotnet run --no-launch-profile --project DLS.EF"
    networks:
      - lan 

  webapi:
    build: ./
    command: "./wait-for-it.sh mssql:1433 -- dotnet run --no-launch-profile --project DLS.WebApi"
    environment:
      ASPNETCORE_URLS: "http://*:80"
    networks:
      - lan
    ports:
      - 8000:80

  # frontend:
  #   build: 
  #     context: ./dls_frontend
  #     dockerfile: ./Dockerfile
  #   volumes:
  #     - ./src:/app/src
  #   environment:
  #     ASPNETCORE_URLS: "http://*:80"
  #   networks:
  #     - lan
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - webapi
    

  servicestudent:
    build: ./
    command: "./wait-for-it.sh mssql:1433 -- dotnet run --no-launch-profile --project DLS.ServiceStudent"
    environment:
      ASPNETCORE_URLS: "http://*:80"
    networks:
      - lan

  serviceteacher:
    build: ./
    command: "./wait-for-it.sh mssql:1433 -- dotnet run --no-launch-profile --project DLS.ServiceTeacher"
    environment:
      ASPNETCORE_URLS: "http://*:80"
    networks:
      - lan

  servicecourse:
    build: ./
    command: "./wait-for-it.sh mssql:1433 -- dotnet run --no-launch-profile --project DLS.ServiceCourse"
    environment:
      ASPNETCORE_URLS: "http://*:80"
    networks:
      - lan

  servicelecture:
    build: ./
    command: "./wait-for-it.sh mssql:1433 -- dotnet run --no-launch-profile --project DLS.ServiceLecture"
    environment:
      ASPNETCORE_URLS: "http://*:80"
    networks:
      - lan
  
  servicenetwork:
    build: ./
    command: "./wait-for-it.sh mssql:1433 -- dotnet run --no-launch-profile --project DLS.ServiceNetwork"
    environment:
      ASPNETCORE_URLS: "http://*:80"
    networks:
      - lan

  servicestatistics:
    build: ./
    command: "./wait-for-it.sh mssql:1433 -- dotnet run --no-launch-profile --project DLS.ServiceStatistics"
    environment:
      ASPNETCORE_URLS: "http://*:80"
    networks:
      - lan

  servicelogin:
    build: ./
    command: "./wait-for-it.sh mssql:1433 -- dotnet run --no-launch-profile --project DLS.ServiceLogin"
    environment:
      ASPNETCORE_URLS: "http://*:80"
    networks:
    - lan